### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by fire** [squat/kilo#1]
How ready is this project to be used in production environments?

**Comment by squat** [comment]
Hi! At the moment this project is running in a few small production environments as the cluster’s only networking provider without any issue. That said, it is still early alpha. The compatibility feature with other networking providers is not ready for production.

What features of the project are important for you?

**Comment by fire** [comment]
The goal of my project is to instance a local game server k8s cluster for testing while connected to a k8s server in the cloud.

I was able to get k3s installs and kilo started with wireguard via https://gist.github.com/fire/4230d4dda69eb25016cf3db0ef1f39ca. Then, I realized I didn't know how to install wireguard on the managed k8s on Digital Ocean.

The feature is same as the local gpu clusters proposal. It is an app that runs on local gpu clusters. The app could be gpu accelerated gaming or machine learning computation. A proxy for udp is on the Digital Ocean Kubernetes to expose the udp ip / service. Latency is not an issue for testing since the client is in the same network. So this uses the vpn feature.

Summary, the main feature is able to connect Kubernetes clouds.

Another use is to secure Kubernetes clusters in the cloud via a full mesh vpn. This may actually be easier to implement, but that's not my focus.

**Comment by squat** [comment]
Got it. Sounds totally reasonable. For this application, the project is quite stable. I’m glad you got it running on K3s! Would you mind consider that config in a PR?

As for DigitalOcean’s K8s offering, I see that by default this installs Cillium for networking. I’m not sure if DO allows customers to swap out networking providers. Separately I’ll need to add Cillium to my list of networking solutions to test and implement compatibility.

**Comment by fire** [comment]
If the managed K8S hosting doesn't work, do you forsee any problems with installing to openshift / k8s and Kilo in a full mesh network between two clusters?

**Comment by squat** [comment]
Just to be sure, you want to run each K8s with a full Kilo mesh and then peer the two clusters, right? This should not be an issue if both clusters are running Kilo as the networking provider.

One thing to keep in mind when peering the clusters is that their allowed IPs must not overlap. The service, pod, and Kilo CIDRs must be different. Ideally their private IP ranges are also different, as this simplifies setup, though if the private IPs overlap, they can safely be edited out of the peer.yaml files generated by kgctl.

**Comment by fire** [comment]
Yes, each K8s with a full Kilo mesh and then peer the two clusters, right?

**Comment by squat** [comment]
Yes, this should work just fine 👍

**Comment by squat** [comment]
Closing since there’s no unresolved question ATM.
