### ISSUE TITLE
Peer to peer communication

### ISSUE THREAD

**Issue by stobias123** [squat/kilo#102]
I've got a gateway server in the cloud, and two peers in locations A and B. 

I can ping from A -> GW. 
I can ping from B -> GW. 

Both A and B can access k8s services, and the GW can connect back to both A and B.

Pings from A->B show "destination host unreachable". Is peer to peer communication with kilo as GW supported?

**Comment by squat** [comment]
Hi @stobias123 are both of these peers behind NAT? If so, then this currently is not supported by Kilo, however it's on the roadmap!

**Comment by stobias123** [comment]
Yes they are both behind nat :( I'll close.

**Comment by squat** [comment]
@stobias123 :/ sorry, this isn't supported today. It's definitely on the road map though. In fact, #109 is asking for exactly this feature! We'll track development in that issue :)
