### ISSUE TITLE
Kilo sets all subnets on peer as allowed ips

### ISSUE THREAD

**Issue by jdloft** [squat/kilo#120]
We're trying to do some funky stuff with Wireguard and k3s. What we ultimately want to do is have a small (3-5 node) k3s cluster with etcd. All traffic between nodes has to be encrypted with Wireguard.

To get etcd to run through WireGuard, we have an interface, `wg0`, already configured with all peers with which etcd can communicate. Then we would use kilo to configure a second WireGuard interface, `kilo0`, for CNI traffic. The problem is that when kilo starts up it configures all subnets on the peers as an allowed ip subnet on `kilo0` which then conflicts with the `wg0` interface. Is there a way to exclude an interface from being included in kilo's allowed IP discovery?

**Comment by AntonOfTheWoods** [comment]
@jdloft that sounds very interesting indeed, any chance you could share how you are setting this up? I actually want to do exactly the same thing but completely forgot about etcd and never got around to closely studying all the network traffic. Thanks!

**Comment by SerialVelocity** [comment]
I've had this running for over a year. You need to set the force private ip address annotation to stop it being detected. There's #15 for disabling the private IP address completely.

**Comment by squat** [comment]
hi @jdloft, can you provide some more details about the node and what are all the subnets being added to the allowed IPs? Currently, Kilo only adds three subnets to the list of a node's allowed IPs:
1. the Pod subnet assigned to that node;
2. the private IP assigned to that node with a `/32` CIDR range; and
3. the node's WireGuard IP, if it is the leader of a location.

1 *must* be present for Pod-to-Pod communication to work across Kilo locations. 2 needs to be present if you want Pods running on the host network namespace of a node to be able to communicate with Pods and nodes in other locations.

**Comment by jdloft** [comment]
@squat I'll see if I can spin up another cluster to test. What I was seeing is that kilo would also add the other `wg0` subnet to the allowed ips. It's fine if those other three are added.

**Comment by squat** [comment]
Thanks, that would be very helpful to help is identify the issue. Perhaps wg0 had an IP address inside the Kilo or Pod CIDRs?

**Comment by jdloft** [comment]
I can't seem to reproduce this at the moment. I'll reopen if I catch this again.
