### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by AntonOfTheWoods** [squat/kilo#143]
Is there any documentation on how things are in terms of updates? 0.1.0 was released a while ago and the example .yamls just use latest. Is there expected to be no problem just to force an upgrade to latest? Is that the general expectation moving forward?
I ask because the new private/only public IP stuff is probably just what I need(ed) and I'm upgrading everything. I may end up doing a complete reinstall of the cluster but I would like to try upgrading in place to see how things work, even if I do reinstall later. Thanks!

**Comment by squat** [comment]
Hi @AntonOfTheWoods 

> Is there expected to be no problem just to force an upgrade to latest? Is that the general expectation moving forward?

Yes that's exactly the idea! The interface hasn't changed as we've only added new features / extensions recently.

@leonnicolas and I are planning on cutting 0.2.0 ASAP as soon as we test https://github.com/squat/kilo/compare/fix_graph_newlines

**Comment by AntonOfTheWoods** [comment]
Perfect, @squat , thanks! Is there somewhere that resumes the current situation for nodes that only have public IPs? I saw the issues go past but was neck deep in "modern JS" (which is far too magical for my aging brain...) so didn't really get what is required now compared with before. I currently have forced values like the following (the nodes don't actually have these addresses):

```
kilo.squat.ai/force-internal-ip: 192.168.222.2/32
kilo.squat.ai/internal-ip: 192.168.222.2/32
```
And upgrading didn't seem to cause the sky to fall. Are these still required?

And might activating Discussions be useful for this project?

**Comment by leonnicolas** [comment]
You can use force-internal-ip: "-" to disable it. See #127

**Comment by squat** [comment]
If the meds don't have private addresses at all, then the annotations aren't needed, but if the nodes have private IPs that you'd like to disable, then, as @leonnicolas said, you can add the annotation to disable them (documented here: https://github.com/squat/kilo/blob/main/docs/annotations.md#force-internal-ip).

However, we don't yet have a doc mentioning how nodes can be fully public or private. This might make sense in the topology doc

**Comment by AntonOfTheWoods** [comment]
> If the meds don't have private addresses at all, then the annotations aren't needed,

Awesome, thanks @squat  and @leonnicolas , so just to make sure - this *wasn't* the case for , i.e, the annotations *were* necessary (or the equivalent via some other mechanism) but they no longer are, meaning if there is only a public IP it will detect that and configure appropriately? I ask because I would like to get rid of my nasty hack but want to make sure that it is no longer necessary for my precise usecase (el cheapo VPSes with only a public IP).

**Comment by squat** [comment]
Yes, that's correct. They used to be necessary but no longer are. Nodes without private IPs can now join clusters automatically without needing extra annotations
