### ISSUE TITLE
Kilo in Cross-LAN communication

### ISSUE THREAD

**Issue by khalid-davis** [squat/kilo#156]
CNI plugins such as flannel often require that the network between nodes are reachable, but in edge scenarios, it often appears that edge nodes and cloud nodes belong to different local area networks, and the cloud nodes are generally assigned public network IP while edge nodes will not.   This phenomenon leads to the failure of pod networks between nodes in different LANs.
Can Kilo solve this kind of Cross-LAN node communication?
Thanks

**Comment by squat** [comment]
Yes, +1 to what @leonnicolas said. Kilo was designed exactly for building cross-cloud, cross-region, cross-network clusters where the nodes are not necessarily in the same network. One of the big goal for Kilo is to enable edge nodes to connect to clusters in the cloud. This has been possible for a while with Kilo and was recently enhanced. As of #146, nodes behind NAT can have full connectivity with other nodes behind NAT, meaning that edge nodes, e.g. IoT devices, can now have full access to the Pod network on other edge nodes and not just the nodes in the cloud.

**Comment by khalid-davis** [comment]
Thanks. 
By the way, is there a tutorial to guide how to deploy this scenario, for example on k3s or kubernetes. 
And from the README.md, I can see that Kilos can collaborate with flannel or other CNIs, and are there related tutorial documents?

**Comment by khalid-davis** [comment]
"Step 4: ensure nodes have public IP
At least one node in each location must have an IP address that is routable from the other locations. If the locations are in different clouds or private networks, then this must be a public IP address. If this IP address is not automatically configured on the node's Ethernet device, it can be manually specified using the kilo.squat.ai/force-endpoint annotation."   
Is this necessary, because in my scenario, there may not any node with public IP in the LAN of my edge nodes.

**Comment by squat** [comment]
This step 4 needs to be updated actually! Only the apiserver must have a publicly routable endpoint so that all nodes in the cluster can makes initial contact with it. All other nodes and locations can be behind NAT

**Comment by khalid-davis** [comment]
OK. That is great.
By the way, is there a tutorial to guide how to deploy this scenario, for example on k3s or kubernetes.
And from the README.md, I can see that Kilos can collaborate with flannel or other CNIs, and are there related tutorial documents?

**Comment by leonnicolas** [comment]
Would it be cool to have some step by step tutorials for some common use cases of Kilo? More detailed and more specific than the README. This could also involve some trouble shooting. Would this make Kilo more accessible? I'd be happy to write something.

**Comment by khalid-davis** [comment]
It will be very good. And step 4 in readme also needs to be updated. A more detailed and more specific documents (for example using k3s or other) can make kilo more accessible.

**Comment by khalid-davis** [comment]
Using kilo in cross-LAN communication, do we need to let different LANs to have different private IP network segments for wireguard?

**Comment by squat** [comment]
closing this for now as the documentation updates that are needed are tracked in https://github.com/squat/kilo/issues/165
