### ISSUE TITLE
The DaemonSet "kilo" is invalid

### ISSUE THREAD

**Issue by iogrids** [squat/kilo#166]
I am getting below error when I run kilo on k3s

```
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/kilo-k3s.yaml
```

The DaemonSet "kilo" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"kilo", "app.kubernetes.io/part-of":"kilo"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10

**Comment by squat** [comment]
Hi @iogrids, 
>field is immutable

means that Kilo was already successfully deployed to your cluster, we changed the Kilo DaemonSet YAML upstream (which we did this afternoon), and you tried to re-apply. To fix this, you'll need to kubectl delete the DaemonSet and then recreate it :))

**Comment by squat** [comment]
Closing this issue now since it seems to be resolved :)
