### ISSUE TITLE
The CustomResourceDefinition "peers.kilo.squat.ai" is invalid: spec.scope: Invalid value: "Namespaced": field is immutable

### ISSUE THREAD

**Issue by Ehco1996** [squat/kilo#198]
i try update kilo to leatest version but i fond there is one crd yaml neen to apply from readme 

```
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/crds.yaml
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/kilo-k3s.yaml
```

but i stuck in first step

```
Warning: resource customresourcedefinitions/peers.kilo.squat.ai is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The CustomResourceDefinition "peers.kilo.squat.ai" is invalid: spec.scope: Invalid value: "Namespaced": field is immutable
```

my k3s version is `v1.21.1+k3s1`

could anyone can help me ?

**BTW**, i think kilo need docker image with release tag, i can do some hlep work if you need

**Comment by leonnicolas** [comment]
Hi @Ehco1996,
You first need to delete the old crd with
```
kubectl delete crd peers.kilo.squat.ai
```
Hope that helps. 

About the release tags, there is a 0.1.0 docker image, but 0.2.0 was never tagged. I think because the ci is not triggered by new releases. Is this what you were thinking about? Maybe this should be handled in a separate issue/pr?

**Comment by Ehco1996** [comment]
@leonnicolas  thanks for your help, and my k3s cluster was upgrade successful

i draft a PR #199  to add taged docker image in release github action
please advise if there is anything wrong
My K3s cluster upgrade was successful

**Comment by squat** [comment]
Glad to hear the upgrade was successful :))) 🚀
