### ISSUE TITLE
How to change MTU after installation?

### ISSUE THREAD

**Issue by Evlos** [squat/kilo#208]
Hi all,

I have installed kilo on my cluster, it's a great project and it runs smoothly.

Since I need to expand my cluster, and the MTU 1420 are too large for some server providers. Therefore I have to change it to 1280.

I tried to change MTU value inside kilo-k3s.yaml and re-apply the file, it seems not working.

```
data:
  cni-conf.json: |
    {
       "cniVersion":"0.3.1",
       "name":"kilo",
       "plugins":[
          {
             "name":"kubernetes",
             "type":"bridge",
             "bridge":"kube-bridge",
             "isDefaultGateway":true,
             "forceAddress":true,
             "mtu": 1280,
```

Then I tried ```kubectl delete -f```, restart the server, make sure kilo0 interface disappeared, then ```kubectl apply -f``` again, I found the MTU is still 1420.

```
node8:~$ ifconfig | grep mtu
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
ens4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
kilo0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1440
veth075d38d4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
veth3dbf4b6f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
vethcb44e5b9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
vethd8b685bd: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
vethf5646d51: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410

node8:~$ cat /etc/cni/net.d/10-kilo.conflist
{"cniVersion":"0.3.1","name":"kilo","plugins":[{"bridge":"kube-bridge","forceAddress":true,"ipam":{"ranges":[[{"subnet":"10.42.4.0/24"}]],"type":"host-local"},"isDefaultGateway":true,"mtu":1280,"name":"kubernetes","type":"bridge"},{"capabilities":{"portMappings":true},"snat":true,"type":"portmap"}]}
```

```
kubectl describe -n kube-system configmap/kilo
Name:         kilo
Namespace:    kube-system
Labels:       app.kubernetes.io/name=kilo
Annotations:  <none>

Data
====
cni-conf.json:
----
{
   "cniVersion":"0.3.1",
   "name":"kilo",
   "plugins":[
      {
         "name":"kubernetes",
         "type":"bridge",
         "bridge":"kube-bridge",
         "isDefaultGateway":true,
         "forceAddress":true,
         "mtu": 1280,
         "ipam":{
            "type":"host-local"
```

```
kube-system      kilo-wdzdx                                1/1     Running     0          39m
kube-system      kilo-q8hjq                                1/1     Running     0          39m
kube-system      kilo-xz59s                                1/1     Running     0          39m
kube-system      kilo-mzkpp                                1/1     Running     0          39m
kube-system      kilo-n2jcm                                1/1     Running     0          39m
kube-system      kilo-w9zmx                                1/1     Running     0          39m
kube-system      kilo-msdsr                                1/1     Running     0          39m
```

Please let me know is there anyway to change MTU after installation? Thank you.

**Comment by Evlos** [comment]
I know I can manually change MTU by ```sudo ip link set kilo0 mtu 1280``` but it seems too casual.

**Comment by squat** [comment]
Hi @Evlos, changing the CNI configuration will only ever change the MTU for the CNI devices, that means the veth pairs and bridge devices on the node. Right now, Kilo does not provide any way to modulate the MTU for the `kilo*` devices; this is a needed feature!

This will certainly be straightforward to implement: we need to add func to the `iproute` package https://github.com/squat/kilo/blob/main/pkg/iproute/iproute.go and explicitly set the MTU after creating our WireGuard interface.

We could make this work via a new `--mtu` flag on the main `kg` binary. WDYT?

**Comment by Evlos** [comment]
> Hi @Evlos, changing the CNI configuration will only ever change the MTU for the CNI devices, that means the veth pairs and bridge devices on the node. Right now, Kilo does not provide any way to modulate the MTU for the `kilo*` devices; this is a needed feature!
> 
> This will certainly be straightforward to implement: we need to add func to the `iproute` package https://github.com/squat/kilo/blob/main/pkg/iproute/iproute.go and explicitly set the MTU after creating our WireGuard interface.
> 
> We could make this work via a new `--mtu` flag on the main `kg` binary. WDYT?

That sounds awesome!
