### ISSUE TITLE
Document required Roles and ClusterRoles for kg

### ISSUE THREAD

**Issue by stv0g** [squat/kilo#210]
We are running Kilo in an Edge-cloud setup with K3S in which we don't fully trust the K3S agent nodes.
Therefore it would be good if we can provide a kubeconfig to the kg daemonset with reduced privileges.

I am looking for the exact Roles and ClusterRoles which are required for `kg` to function.

**Comment by squat** [comment]
Nice suggestion @stv0g. So you mean creating a document to formally record the RBAC that we have in the manifests, e.g. https://github.com/squat/kilo/blob/main/manifests/kilo-kubeadm.yaml#L40-L80?

These are the minimum set for correct operation. There's a mistake there actually, Kilo no longer requires update permissions on Peers (thanks to new NAT discovery).

If you want to further lock down every node, then you would likely be well served to ensure that every kg instance has a dedicated ServiceAccount with a ClusterRole that restricts access to only make patch updates to its own node, e.g. via
```yaml
resources: ["nodes"]
resourceNames: ["node-x"]
verbs: ["watch", "list", "patch"]
```

**Comment by stv0g** [comment]
Hi @squat,

Oh thanks for the hint. I was not aware that the ServiceAccount in the manifest has already proper Roles assigned to it.
