### ISSUE TITLE
Peer endpoints are set to 127.0.0.1

### ISSUE THREAD

**Issue by sbaildon** [squat/kilo#229]
Treading off the beaten bath a little here.

* Running a k3s cluster on hetzner
* Using their VPC
* Using their external cloud-controller https://github.com/hetznercloud/hcloud-cloud-controller-manager
* Flannel disabled, using kilo as the CNI

Everything mostly works, but I have to manually annotate nodes with `squat.kilo.ai/force-endpoint`, using the node's allocated VPC address from my `10.0.0.0/16` subnet because `kilo` is configuring all peer IPs as `127.0.0.1:51820`. Once I've overridden those, everything is great.

This is where my domain knowledge breaks down—do you know if 1) `kilo` is missing something it _could_ be parsing, 2) hetzner's ccm not setting a value, or 3) ???

**Comment by squat** [comment]
Hi @sbaildon :) that doesn't sound too different from setups I've run on Hetzner myself!

The Kilo agent running on each node tries to discover the "best" IP address to advertise to the rest of the cluster by looking at the IP addresses that are assigned to any interface on the host and prioritizing public IP addresses. Cloud you log onto one of the nodes and share the output of `ip a`? Also, could you share the corresponding logs from that node's kilo container?

**Comment by sbaildon** [comment]
> Hi @sbaildon :) that doesn't sound too different from setups I've run on Hetzner myself!
> 
> The Kilo agent running on each node tries to discover the "best" IP address to advertise to the rest of the cluster by looking at the IP addresses that are assigned to any interface on the host and prioritizing public IP addresses. Cloud you log onto one of the nodes and share the output of `ip a`? Also, could you share the corresponding logs from that node's kilo container?

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 96:00:00:d4:a6:ea brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 95.216.215.117/32 scope global dynamic noprefixroute eth0
       valid_lft 86213sec preferred_lft 86213sec
    inet6 2a01:4f9:c010:4c8e::1/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::9400:ff:fed4:a6ea/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether 86:00:00:d4:a6:f0 brd ff:ff:ff:ff:ff:ff
    altname enp0s10
    inet 10.0.0.3/32 brd 10.0.0.3 scope global dynamic ens10
       valid_lft 86277sec preferred_lft 86277sec
    inet6 fe80::8400:ff:fed4:a6f0/64 scope link 
       valid_lft forever preferred_lft forever
4: kilo0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.4.0.1/16 brd 10.4.255.255 scope global kilo0
       valid_lft forever preferred_lft forever
5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.42.6.1/32 brd 10.42.6.1 scope global tunl0
       valid_lft forever preferred_lft forever
6: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1420 qdisc noqueue state UP group default qlen 1000
    link/ether 46:ac:f8:6d:cc:7f brd ff:ff:ff:ff:ff:ff
    inet 10.42.6.1/24 brd 10.42.6.255 scope global kube-bridge
       valid_lft forever preferred_lft forever
    inet6 fe80::44ac:f8ff:fe6d:cc7f/64 scope link 
       valid_lft forever preferred_lft forever
7: veth158cecc2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1420 qdisc noqueue master kube-bridge state UP group default 
    link/ether ce:5c:11:06:52:f9 brd ff:ff:ff:ff:ff:ff link-netns cni-27fd9596-a456-e166-d4c8-920fed962935
```

```
[root@master ~]# kubectl get pods -o wide --field-selector spec.nodeName=cx11-0
NAME                    READY   STATUS    RESTARTS   AGE     IP          NODE     NOMINATED NODE   READINESS GATES
kilo-bjlxd              1/1     Running   0          4m53s   10.0.0.3    cx11-0   <none>           <none>
```

```
[root@master ~]# kubectl  logs kilo-bjlxd
{"caller":"mesh.go:96","component":"kilo","level":"warn","msg":"no private key found on disk; generating one now","ts":"2021-08-22T09:45:55.688529783Z"}
{"caller":"main.go:222","msg":"Starting Kilo network mesh 'e886f5d24ef8b0065d3f01289bad9153c3facc67'.","ts":"2021-08-22T09:45:55.82854351Z"}
{"caller":"cni.go:60","component":"kilo","err":"failed to read IPAM config from CNI config list file: no IP ranges specified","level":"warn","msg":"failed to get CIDR from CNI file; overwriting it","ts":"2021-08-22T09:45:56.031552966Z"}
{"caller":"cni.go:68","component":"kilo","level":"info","msg":"CIDR in CNI file is empty","ts":"2021-08-22T09:45:56.032180613Z"}
{"CIDR":"10.42.6.0/24","caller":"cni.go:73","component":"kilo","level":"info","msg":"setting CIDR in CNI file","ts":"2021-08-22T09:45:56.032582943Z"}
{"caller":"mesh.go:297","component":"kilo","event":"add","level":"info","node":{"Endpoint":{"DNS":"","IP":"127.0.0.1","Port":51820},"Key":"ZWFObGFGNnM3dXZLWWZGRVBFT2tSV2lTTVFKUkFvVU1XVlI3dW1WdDcwND0=","NoInternalIP":false,"InternalIP":{"IP":"10.0.0.2","Mask":"/////w=="},"LastSeen":1629625545,"Leader":false,"Location":"fsn1","Name":"master","PersistentKeepalive":0,"Subnet":{"IP":"10.42.0.0","Mask":"////AA=="},"WireGuardIP":{"IP":"10.4.0.1","Mask":"//8AAA=="},"DiscoveredEndpoints":{},"AllowedLocationIPs":null,"Granularity":"location"},"ts":"2021-08-22T09:45:56.229439369Z"}
{"caller":"mesh.go:536","component":"kilo","level":"info","msg":"WireGuard configurations are different","ts":"2021-08-22T09:45:56.397826173Z"}
{"caller":"mesh.go:297","component":"kilo","event":"update","level":"info","node":{"Endpoint":{"DNS":"","IP":"127.0.0.1","Port":51820},"Key":"ZWFObGFGNnM3dXZLWWZGRVBFT2tSV2lTTVFKUkFvVU1XVlI3dW1WdDcwND0=","NoInternalIP":false,"InternalIP":{"IP":"10.0.0.2","Mask":"/////w=="},"LastSeen":1629625575,"Leader":false,"Location":"fsn1","Name":"master","PersistentKeepalive":0,"Subnet":{"IP":"10.42.0.0","Mask":"////AA=="},"WireGuardIP":{"IP":"10.4.0.2","Mask":"//8AAA=="},"DiscoveredEndpoints":{},"AllowedLocationIPs":null,"Granularity":"location"},"ts":"2021-08-22T09:46:15.757333295Z"}
```

```
[root@master ~]# wg
interface: kilo0
  public key: eaNlaF6s7uvKYfFEPEOkRWiSMQJRAoUMWVR7umVt704=
  private key: (hidden)
  listening port: 51820

peer: 9XGZL2zl89eulFiusUbBu3UstBwG8w8z9nr1KRPRQDM=
  endpoint: 127.0.0.1:51820
  allowed ips: 10.42.6.0/24, 10.0.0.3/32, 10.4.0.1/32
  transfer: 0 B received, 12.00 KiB sent
```

**Comment by sbaildon** [comment]
I did some poking around with fresh eyes and found that https://github.com/squat/kilo/blob/e886f5d24ef8b0065d3f01289bad9153c3facc67/pkg/mesh/discoverips.go#L160

is including the loopback address in the public list

```go
fmt.Printf("public: %s\n", pub)
fmt.Printf("private: %s\n", priv)

fmt.Printf("\n")

fmt.Printf("selected\npriv: %s\npub: %s\n", priv[0], pub[0])
```

```
public: [127.0.0.1/8 ::1/128 95.217.233.247/32 2a01:4f9:c011:3d1b::1/64 95.217.233.247/32 2a01:4f9:c011:3d1b::1/64]
private: [10.0.0.3/32 10.4.0.2/16 10.42.7.1/24 10.42.7.1/32]

selected
priv: 10.0.0.3/32
pub: 127.0.0.1/8
```

**Comment by sbaildon** [comment]
> IP addresses that are assigned to any interface on the host and prioritizing public IP addresses

What are your opinions on an annotation (or flag?) that prioritises private IP addresses?

If deploying a cluser to a cloud provider across regions with a shared VPC, I'd probably want my traffic to stay inside the VPC  to limit any bandwidth egress charges or slower links

**Comment by squat** [comment]
Great work looking through the code and thanks for the info!

Yes absolutely, if you notice, the loops above your patch explicitly exclude local addresses by using the `isLocal` helper however the loop on https://github.com/squat/kilo/blob/main/pkg/mesh/discoverips.go#L66-L80 does not. This `isLocal`check would be good to here as well. Loopback address are excluded everywhere else in the code, which suggests that we are discovering this address from your hostname.

Kilo only sorts each "group" of IPs, so even though the real public IP is discovered, the loopback address is chosen because the hostname of your machine resolves to this.

1. We should fix the behavior of the discovery of IPs from the hostname by adding a check for `if isLocal(ip.IP){continue}` like the other blocks do, right before line 74. Maybe it's a bit funny that your hostname resolves to the loopback address, but this change should catch this case. Would you like to make this PR?
2. I'm not at all against the idea of a configuration option to prioritize private IPs change; I totally see the value. I think this may be easier to implement as a flag than as an annotation because the IP discovery code currently only happens once during the initialization of the mesh and not in a loop that can be influenced by annotations. That said, we could also move the IP discovery into the loop, but this will require a bit more refactoring.

**Comment by squat** [comment]
Let's close this since #230 fixes the issue :heart: thanks again for the fix!
