### ISSUE TITLE
Include Example WireGuard Exporter DaemonSet

### ISSUE THREAD

**Issue by squat** [squat/kilo#234]
I think it could be useful for users to know how to monitor the Kilo mesh in their clusters. For this, we could leverage an existing project that implements a Prometheus exporter for WireGuard, e.g. https://github.com/MindFlavor/prometheus_wireguard_exporter.

I propose we write an example DaemonSet for this exporter along with a matching PodMonitor and include them in our manifests directory. We could then add a page to our docs explaining how to monitor Kilo with Prometheus and suggest using this new configuration in conjunction with our existing PodMonitor.

**Comment by leonnicolas** [comment]
this was merged with https://github.com/squat/kilo/pull/251
