### ISSUE TITLE
etcd traffic not going through the Kilo interface 

### ISSUE THREAD

**Issue by sandah** [squat/kilo#246]
Hi,
I have a cluster (3 master nodes) with an embedded etcd that was set up with K3S and --no-flannel flag.
After installing Kilo with --mesh-granularity=full argument, it's working except the etcd peer communication traffic which is not going through the Kilo tunnel.

Is there a reason why? 
What can I do to make it work?

**Comment by Sandah** [comment]
Hi
Thanks for the answer,
I didn't test it yet but I think I found a solution to achieve what I want with the help of this thread #120.

**Comment by squat** [comment]
hi @Sandah any luck?
You should be able to accomplish this if you modify your etcd endpoints to use the internal IPs of the nodes. This will force the connections to be over the WireGuard link.
Any luck?

**Comment by sandah** [comment]
Hi @squat, unfortunately, I hadn't had time to try it and as you said etcd traffic is already encrypted so it’s kind of pointless.. I think it’s time to close this. Thanks again!
