### ISSUE TITLE
Err info `kilo.squat.ai/internal-ip`, got `127.0.0.1`

### ISSUE THREAD

**Issue by huapox** [squat/kilo#25]
**Problem:**

I'm using `squat/kilo:amd64-c93fa1e5b194e5d0a847f0775033bed92251f4d6`

Add a new node `ten-vm1`got err info `kilo.squat.ai/internal-ip` with `127.0.0.1`, cause err route in other node:

```base
[root@hw-vm1 ~]# route -n |grep kilo
127.0.0.1       10.4.0.3        255.255.255.255 UGH   0      0        0 kilo0
```

**Resolv:**

Cur I just use `kubectl annotate node ten-vm1 kilo.squat.ai/internal-ip="172.21.0.xx/32" --overwrite=true` to fix this err info.

**Comment by squat** [comment]
fixed by https://github.com/squat/kilo/pull/104
