### ISSUE TITLE
kgctl list nodes/peers

### ISSUE THREAD

**Issue by theonlydoo** [squat/kilo#252]
it appears that you have to know nodes/peers names to `showconf`, it'd be nice to have a `kubectl get nodes` style command.

**Comment by leonnicolas** [comment]
Hey, @theonlydoo, sorry for the delay. I am still not sure what you propose exactly. Can you give an example output of the proposed commands?

Anyways, PRs welcome :)

**Comment by squat** [comment]
ping @theonlydoo
This sounds like it should be a pretty simple feature. Could you share any more idea you had about the desired outputs you would find useful?

**Comment by theonlydoo** [comment]
hey guys! sorry for the delayed response. I totally forgot about this issue. I can't seem to remember what was behind :thinking:

**Comment by squat** [comment]
That was fast :)
No worries. We're trying to put together more ideas from the community to drive feature planning for the project so any input is welcome.

I'll close this for now. Naturally, please re-open if you have any more ideas:0
