### ISSUE TITLE
kilo fails if IPv6 is disabled via ipv6.disable=1 (kernel-cmdline)

### ISSUE THREAD

**Issue by aholler** [squat/kilo#259]
If IPv6 is disabled via ipv6.disable=1 in the kernel command line, kilo fails with

{"caller":"mesh.go:521","component":"kilo","error":"failed to add rule: failed to add iptables chain: running [/sbin/ip6tables -t nat -N KILO-NAT --wait]: exit status 3: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n","level":"error","ts":"2022-01-04T07:11:44.22190937Z"}

The result is that the wireguard interface will not be enabled and tunneling won't work (using 0.3.1).

Best regards,

Alexander Holler

**Comment by squat** [comment]
Hi @aholler, yes that is a very good catch. Indeed i can see why this occurs, as we try to start iptables controllers for both protocols to be ready for whatever may come. I think this should be quite straightforward to fix

**Comment by squat** [comment]
@aholler we finally unblocked CI
this issue should be happily resolved now :) If possible, could you try the latest Kilo tag squat/kilo:76047fe0affd60e4828db36fea6a540f9d7e0bb7 on your cluster and let us know if this fixed the problem you reported?

**Comment by aholler** [comment]
@squat works:

{"caller":"iptables.go:278","component":"iptables","level":"info","msg":"IPv6 is disabled in the kernel; disabling the IPv6 iptables controller","ts":"2022-01-07T05:49:21.102871067Z"}

Thanks a lot!
