### ISSUE TITLE
Disconnections every 30s

### ISSUE THREAD

**Issue by segator** [squat/kilo#267]
2 Locations.
A with static public IP
B with dynamic public IP (NAT)

if I do ping from B to A using WG internal IP works but every 30s stops working, checking the logs of kilo appears that is refreshing the IP with the content of annotation kilo.squat.ai/endpoint that seems is wrongly discovered, discovering my internal IP instead of public IP. When seems connection works and check wg command on A the IP setted on the peer is OK.
It will be nice if kilo can just use the IP discovered by wireguard and roam to all nodes.

| annotations |
| --- |
| kilo.squat.ai/discovered-endpoints: {}
| kilo.squat.ai/endpoint: 192.168.1.34:51820 |
| kilo.squat.ai/granularity: location |
| kilo.squat.ai/internal-ip: 192.168.1.34/24 |

**Comment by segator** [comment]
Ignore it, after setting keep-alive the discovered-endpoints seems is filled correctly and doing proper roaming!

What i notice is when using kgctl showconf peer xxxx is not  populating the IP's with those discovered  "discovered-endpoints"

it will be nice for outside of cluster peers to allow kgctl to set the endpoints with the discovered-endpoints aswell some kind of "daemon mode" so can pull updates  on IP's or new nodes.

**Comment by segator** [comment]
Also when adding external peer the roaming to this peer is not updated to other nodes on the cluster.
Imagine the case in cluster
2 Locations.
A with static public IP
B with dynamic public IP (NAT)

and external peer in NAT (C)

In this case ideally we should be able to discover the External peer(C) IP from A and send the connection info to B, so B can connect to C

**Comment by squat** [comment]
Ah that should really be the case. And if in fact it's not, then it should absolutely be a feature! kgctl *should* use the discovered-endpoints annotation of all of the nodes in the cluster to determine IPs for the NATed peers.

**Comment by squat** [comment]
Ah that should really be the case. And if in fact it's not, then it should absolutely be a feature! kgctl *should* use the discovered-endpoints annotation of all of the nodes in the cluster to determine IPs for the NATed peers.

**Comment by squat** [comment]
Ah that should really be the case. And if in fact it's not, then it should absolutely be a feature! kgctl *should* use the discovered-endpoints annotation of all of the nodes in the cluster to determine IPs for the NATed peers.

**Comment by segator** [comment]
No its not rendering based on the discovery, also it will be nice if kg can run in external node only somehow, to track changes and update peers on the "edge"

**Comment by squat** [comment]
Yes we've thought about this same feature before. In fact, there's an existing open issue to track this. Of course you can use kgctl and some shell scripts to accomplish this but it would be very convenient to have a daemon that does this for you automatically on, e.g., a laptop

**Comment by segator** [comment]
that would be awesome!

**Comment by squat** [comment]
Hi @segator we just closed issue #273, which seems like it was the same as this one. Can you please try the latest version of Kilo to see if indeed the problem you experienced is gone?

**Comment by squat** [comment]
Btw https://github.com/squat/kilo/issues/267#issuecomment-1025043692 would be fixed by #269

**Comment by squat** [comment]
all of this is officially done now that #269 is merged :)) :tada:
