### ISSUE TITLE
How to clear all `kilo`-related state?

### ISSUE THREAD

**Issue by brianthelion** [squat/kilo#281]
`kilo` performs updates to the node filesystem and networks. As a result, it may be necessary to execute manual teardown steps on the node to return it to a "pristine" state in the event of a `kubeadm reset` or `apt-get purge kubelet`, etc.

What are the steps that should be taken to flush all `kilo`-related state from a node?

**Comment by squat** [comment]
hi @brianthelion, Kilo will reset almost everything during its cleanup phase. This means, it should remove:
* routes;
* WireGuard ethernet devices, i.e. the kiloX device;
* any encapsulation ethernet devices, i.e. the tun0 interface;
* iptables rules; and
* The Kilo annotations on Kubernetes resources.

The things that will _not_ be automatically cleaned are:
* the WireGuard private keys that Kilo automatically generates and places in `/var/lib/kilo`; 
* the CNI binaries located at `/opt/cni/bin/`; and
* the Kilo CNI configuration located at `/etc/cni/net.d/10-kilo.conflist`.

_Note_: if you are using a Kilo version before https://github.com/squat/kilo/pull/239 was merged, then you will also have a WireGuard configuration INI located at `/var/lib/kilo/conf`

**Comment by brianthelion** [comment]
@squat Thanks, this is super helpful.

My operating assumption is that a `kubeadm reset --force` will fail to trigger the cleanup phase, so I will manually need to deal with the routes and iptables rules.

As an aside, what are the conditions under which the cleanup phase is triggered? Is there a way to trigger it from the node console directly, eg, via `docker exec` on the `kilo` container?

**Comment by squat** [comment]
Closing this for now, since it seems all of the needed information is in the issue. Please reopen if any information is missing!
