### ISSUE TITLE
When is release 0.4.0 or 0.3.2 planned?

### ISSUE THREAD

**Issue by clive-jevons** [squat/kilo#282]
Hi 😊

First off - thanks for this excellent project - it's been very useful and very stable for us ❤️

Was wondering for when the next release is planned? We'd like to pin our deployments to a more recent version 😬

Cheers,
C

**Comment by leonnicolas** [comment]
I think we could release 0.4.0 soon (maybe merge/finish the open PRs). We added some features, so it won't be a 0.3.2.

If you don't want to wait, you can always pin to the latest digest, which would be `squat/kilo:a1af9790ea541c683d528d5a1d23075528d682d4`.

**Comment by squat** [comment]
I'd like to get #269 merged for 0.4.0. hopefully we can ge that merged this week and then we can cut a new release 🎉

**Comment by clive-jevons** [comment]
Wondering if there's an update? Maybe even something I could help with?

**Comment by squat** [comment]
Almost done! Trying to get the last point here wrapped up so we can merge the PR and cut the release: https://github.com/squat/kilo/pull/269#pullrequestreview-929654128

**Comment by squat** [comment]
It's officially out! :tada:

**Comment by clive-jevons** [comment]
AWESOME! Thank you!! 😍
