### ISSUE TITLE
Installation of a release should use that release's image tag

### ISSUE THREAD

**Issue by clive-jevons** [squat/kilo#290]
I installed `v0.4.0` to one of our clusters, but noticed that the image being pulled was still `squat/kilo:latest`. Checking in https://github.com/squat/kilo/blob/0dfb7446302cdcb08cb991019885f28e313dd67c/manifests/kilo-kubeadm.yaml#L104 I saw that the manifest of the release only specifies `squat/kilo`.

Would it be possible to add tagged image versions corresponding to the release?

**Comment by squat** [comment]
yes definitely :) I can get to it later today, otherwise, please feel free to make a PR to the release-0.4 branch!

**Comment by clive-jevons** [comment]
I'll have a go at a PR 👍

**Comment by squat** [comment]
hm I prefer not to re-tag once we've published to the wild. However, we can happily cut 0.4.1 with this fix :) so, we'll have to bump the manifests to be 0.4.1 and merge this to the release-0.4 branch and then we can tag a new release. WDYT?

**Comment by clive-jevons** [comment]
Have prepared https://github.com/squat/kilo/pull/292 with the version bump to the referenced images 👍
