### ISSUE TITLE
kgctl release

### ISSUE THREAD

**Issue by fire** [squat/kilo#3]
No releases for kgctl on Github. I suppose it has to be compiled?

**Comment by squat** [comment]
Yes, that’s the the current state. This should be added to the docs. Perhaps under a new file docs/kgctl.md. After the first release I’ll publish binaries too.

**Comment by SerialVelocity** [comment]
Could you put the kgctl inside the docker image for now? That way we can either extract it or run it with `kubectl exec`

**Comment by squat** [comment]
This has been implemented in https://github.com/squat/kilo/pull/111 and binaries will automatically get build and uploaded in the next release :tada:
