### ISSUE TITLE
After updating new location can't "phone home" before external IP forced

### ISSUE THREAD

**Issue by clive-jevons** [squat/kilo#308]
We have a multi-cloud setup with node pools communicating via kilo.
The "external" node pools (e.g. the ones not co-located with the control plane) are on GCP and don't know their external IP to begin with.

Previously, they were still able to make calls to the kube-api via kubectl event before knowing their external-ip - which allowed us to write a small controller run on the new nodes via a DaemonSet which would determine the external-ip and then annotate the Node resource with the `force-endpoint` annotation to finish the setup.

After updating to 0.4.1 this last step isn't possible any more - calls to the kube-api from the new nodes times out.

We currently suspect that a change to the routing setup _might_ be the cause of this, but wanted to ask if anyone can think of any recent changes which would result in this behaviour?
(we're currently rolling back to 0.3.1 where our intended setup works again).

Thanks in advance for any feedback / input.
We'll add comments with updates if we find out anything more ...

**Comment by squat** [comment]
Hi @clive-jevons, so the custom controller is entirely unable to contact the API? Presumable for the controller to work before the endpoint is configured, it must be using a kubeconfig with a public endpoint for the API and _not_ the in-cluster kubeconfig, which uses the `kubernetes` service clusterIP, right?

**Comment by clive-jevons** [comment]
Hi @squat <- actually it was working with using the in-cluster kubernetes service (which, as you implied, points at `10.96.0.1`). No custom kubeconfig involved.

We actually also verified that using such a kubeconfig going against a public IP (or rather DNS name) works. That would be a fallback workaround ... but preferably we'd like to get it working like it did before LOL 😂

**Comment by squat** [comment]
The fact that the in-cluster API worked at all before the force-endpoint annotation was set implies to me that the force-endpoint annotation wasn't even needed in your setup: the Kilo location holding your control-plane was somehow aware of your GCP location and the pod network was already fully connected.

Because of this, I'm a bit confused by the extra controller was necessary. And what exactly it was achieving. I only bring this up because I'm trying to imagine how discovery was _actually_ working before and why it may _not_ be working now. In other words, discovery seems like it was working even without the controller but now it's not working.

**Comment by squat** [comment]
If you're available, please reach out on the Slack channel so we can chat more real-time :)

**Comment by dajudge** [comment]
Maybe helpful in undestanding what's going on: what @clive-jevons and I observed when not setting the force-endpoint annotation was that communication from the control plane to the kubelet was not working (e.g. `kubectl logs` would time out until we force-endpointed the public IP of the GCP node via our controller).

**Comment by clive-jevons** [comment]
Maybe a stupid question - but where can I find the Slack channel 😬  (checked the docs, but found no link ...)

What we had previously was that before setting the `force-endpoint` annotation the 'external' nodes were able to talk to the kube api, but the kube api was not able to talk to the external nodes - e.g. you couldn't do a `kubectl log` for pods running on the external nodes.

**Comment by squat** [comment]
Please join the `#kilo` channel in the k8s Slack: https://slack.k8s.io/
(it's one of the badges at the top of the README.md)

**Comment by clive-jevons** [comment]
We were able to track down the problem, which ended up being a failure on our automated node setup. Discussion on Slack: https://kubernetes.slack.com/archives/C022EB4R7TK/p1650981806238329 

It turned out that due to the failure in setup the `UDP:51820` ingress rule was not being applied in our AWS cluster, which resulted in the GCP nodes not being able to talk to it. After fixing this, everything worked as expected. Huge thanks to @squat  for the support - learned a lot about both `kilo` and `wireguard` along the way 😍
