### ISSUE TITLE
no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by outbackdingo** [squat/kilo#32]
kubectl apply -f https://raw.githubusercontent.com/squat/modulus/master/wireguard/daemonset.yaml
error: unable to recognize "https://raw.githubusercontent.com/squat/modulus/master/wireguard/daemonset.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Comment by squat** [comment]
Yes totally, we need to update the manifests to use the new API group in order to support Kubernetes 1.17. PRs welcome :) otherwise I will get to it this week 👍

**Comment by squat** [comment]
@outbackdingo thanks for reporting this :)

this is now fixed by https://github.com/squat/modulus/commit/89bfe3a82185e4ea809ab7811ec6b2ef6e6b48e5 :tada: . Please note that this driver installer only works for Container Linux and its derivatives, e.g. Flatcar Linux.

**Comment by outbackdingo** [comment]
Please note that this driver installer only works for Container Linux and its derivatives, e.g. Flatcar Linux. ??? So your saying it will not work on a CentOS based Kubernetes cluster ???

**Comment by squat** [comment]
Hi @outbackdingo Kilo will absolutely work on a CentOS-base k8s cluster, however, https://github.com/squat/modulus/ is a project designed specifically for Container Linux and will not work on other distributions. For CentOS, the easiest way to install WireGuard is to run yum on the nodes as described here: https://www.wireguard.com/install/#centos-8-module-tools
