### ISSUE TITLE
Kilo exited unexpectedly: failed to initialize peer backend: CRD is not present: customresourcedefinitions.apiextensions.k8s.io "peers.kilo.squat.ai" not found

### ISSUE THREAD

**Issue by aliuq** [squat/kilo#321]
kilo status is always `CrashLoopBackOff` and got belows error each one
```
Defaulted container "kilo" out of: kilo, generate-kubeconfig (init), install-cni (init)
{"caller":"main.go:280","msg":"Starting Kilo network mesh '0.5.0'.","ts":"2022-07-19T14:22:35.919966141Z"}
error: Kilo exited unexpectedly: failed to initialize peer backend: CRD is not present: customresourcedefinitions.apiextensions.k8s.io "peers.kilo.squat.ai" not found
```

![image](https://user-images.githubusercontent.com/11707934/179774934-9f43fd33-8a45-4fa5-830c-f7761f6a78e5.png)

**Comment by squat** [comment]
Hi @aliuq
Have you installed the CRDs? i.e. `kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/crds.yaml`
This should be the first step in any Kilo [installation process](https://github.com/squat/kilo#step-5-install-kilo).

**Comment by aliuq** [comment]
@squat thanks for your reply, I tried apply and it works now, I referenced [this tutorial](https://icloudnative.io/posts/use-wireguard-as-kubernetes-cni/#2-kilo-%E9%83%A8%E7%BD%B2)

**Comment by leonnicolas** [comment]
> @squat thanks for your reply, I tried apply and it works now, I referenced [this tutorial](https://icloudnative.io/posts/use-wireguard-as-kubernetes-cni/#2-kilo-%E9%83%A8%E7%BD%B2)

fyi @yangchuansheng
