### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Pseudow** [squat/kilo#325]
Hello, I am a bit **lost**, I have tried to follow the **documentation** but I got more **confused**. So I had to ask a few questions:
 - Does kilo required `wireguard` **already setup**? In this case should I add the annotation `force-endpoint` redirecting to the **port of** `wireguard`?
 
 - Will kilo modify my `NAT node address`? Because I think it will cause a problem if it is still its private ip.

 - Should I **setup any cni** or it is actually done by Kilo?

**Comment by squat** [comment]
Hi @Pseudow,
To answer your questions:
1. Kilo automatically set WireGuard up. It will try to discovery the public and private IPs of your machine using various methods and heuristics. However, if Kilo cannot discover the correct endpoint for a host, then the `force-endpoint` annotation can be used to tell the Kilo agent on which port it should listen as well as what IP/DNS name other peers can find the node.
2. I'm not sure what you mean by "modify my `NAT node address`". Kilo does not modify the IP addresses of any nodes anywhere. It "only" configures WireGuard. Kilo is able to configure a WireGuard mesh that traverses some/most NAT boxes but it does not need to modify any IP addresses to do that.
3. This is up to you. Kilo is a full CNI implementation and is designed to work on its own. Optionally, you can install Flannel or Cilium and run Kilo in "add-on" mode. Running Kilo by itself is the most stable and tested way to use Kilo today.

**Comment by Pseudow** [comment]
Actually I installed **kilo**, but I found out that he was **taking the private ip address instead of the public** one so to fix that I just have to add **the annotation** and it will do everything? I won't have to **change anything else**?

**Comment by Pseudow** [comment]
And by the way, should I add the wireguard port to the `force-endpoint` annotation ip address that kilo created?
