### ISSUE TITLE
The pod kilo-* in node was evicted when the memory is out

### ISSUE THREAD

**Issue by aliuq** [squat/kilo#329]
Hi, I have two nodes, there is a lower node because of out of memory and got evicted

```bash
The node was low on resource: memory. Container kilo was using 30332Ki, which exceeds its request of 0.
```

**Comment by squat** [comment]
Hi @aliuq, our manifests don't have any resource requests or limits. This suggests to me that your cluster has some policy or mutating webhook that is automatically adding resource requests/limits to all containers, which is resulting in a request for 0Mib of memory, which is clearly exceeded.

To fix this, I would suggest adding resource requests to the Kilo manifests you are deploying to your cluster.

**Comment by aliuq** [comment]
@squat thank you, I will try it
