### ISSUE TITLE
Add Kilo in Cilium USER.md

### ISSUE THREAD

**Issue by arpagon** [squat/kilo#333]
Hi @squat We love the work done to integrate kilo and cilium. 

Cilium, because of the CNCF graduation, they ask me to add Kilo in  https://github.com/cilium/cilium/blob/master/USERS.md

If you wish, I can add it myself?

```
* N: kilo
  D: Cilium is a supported CNIs in kilo, Cilium + Kilo creates a full mesh via Wireguard for Kubernetes in the edge enviroments.
  U: CNI, Networking, Hubble, kube-proxy replacement, network policy
  L: https://kilo.squat.ai/
  Q: @squat, @arpagon
```

**Comment by squat** [comment]
Thanks @arpagon!
Please go ahead :) i would suggest the following wording:

```
* N: Kilo
  D: Cilium is a supported CNI for Kilo. When used together, Cilium + Kilo create a full mesh via WireGuard for Kubernetes in edge environments.
  U: CNI, Networking, Hubble, kube-proxy replacement, network policy
  L: https://kilo.squat.ai/
  Q: @squat, @arpagon
```

**Comment by arpagon** [comment]
🙏

**Comment by arpagon** [comment]
It's done, [Here](https://github.com/cilium/cilium/blob/b33adeb6f88701979d98095149d6ecb359dc8812/USERS.md?plain=1#L238)

**Comment by onching** [comment]
(Sorry for posting on an old post)

>  Cilium is a supported CNI for Kilo. When used together, Cilium + Kilo create a full mesh via WireGuard for Kubernetes in edge environments.

Is this a bit misleading? wouldn't Kilo + Cilium force kilo into add-on mode (vpn + multi-cluster only) and not support a "full mesh" via wireguard? Or am I missing something?

@arpagon google returned this diagram https://arpagon.co/blog/k8s-edge/ ... I don't think this topology is possible kilo is put into addon mode.

@squat I would really appreciate a clarification. I'm actually looking for a topology like arpagon's diagram but I don't think that's currently supported by kilo.

Thanks
