### ISSUE TITLE
kilo interrupts existing connections every 30s between a public master and a node behind NAT

### ISSUE THREAD

**Issue by carlosrmendes** [squat/kilo#34]
Hi,
I have one master node in region A with a public ip and a worker node in region B behind a NAT (two separate networks).

After deploy Kilo I annotated both nodes to force external ip (master with own public ip and worker with NAT public ip) and to set the related location on each (master: region-a, worker: region-b).

Checking the wireguard peers in the master, with wg command, I can see the peer of the worker, with the NAT public ip as endpoint, but the port is different than the wireguard listen port set on the worker node.

I can also see that the an handshake was made successfully, but after 30s approximately, the Kilo recreate the peer because it detects differences on configuration (log: 'WireGuard configurations are different'), due to the endpoint port and interrupting existing connections.

How can I solve this?
Thanks in advance.

**Comment by squat** [comment]
Hi @carlosrmendes thanks for taking the time to file the issue :)

This typically happens because WireGuard simplifies the configuration that Kilo applies, or because the endpoints change after Kilo applies the configuration. It would be helpful to see the WireGuard configuration file in order to figure out what field is being changed, which will then help us narrow down why it's changing.

We want to see the configuration from WireGuard's point of view [1] as well as from Kilo's point of view [2]. Please share the output of running the following commands on the node whose configuration is changing:
1. `sudo wg showconf kilo0`
1. `sudo cat /var/lib/kilo/conf`

**Comment by carlosrmendes** [comment]
On master node with public ip. The peer refers to a worker node behind a NAT.

`cat /var/lib/kilo/conf`
```
[Interface]
PrivateKey = +HtKt2njk+z5eS2x+JcVlatzEyqBq+F3o62ISsmWnUo=
ListenPort = 51820

[Peer]
AllowedIPs = 10.42.1.0/24, 10.10.11.231/32, 10.4.0.2/32
Endpoint = 18.202.215.77:51820
PersistentKeepalive = 5
PublicKey = 9bmlFlwQ8AEu5g4KvsJF0vnRkI78mJ9I3KQVtd6ctQo=
```

`wg showconf kilo0`
```
[Interface]
ListenPort = 51820
PrivateKey = +HtKt2njk+z5eS2x+JcVlatzEyqBq+F3o62ISsmWnUo=

[Peer]
PublicKey = 9bmlFlwQ8AEu5g4KvsJF0vnRkI78mJ9I3KQVtd6ctQo=
AllowedIPs = 10.42.1.0/24, 10.10.11.231/32, 10.4.0.2/32
Endpoint = 18.202.215.77:51820
PersistentKeepalive = 5
```

`wg showconf kilo0` after an handshake but during 30s only
```
[Interface]
ListenPort = 51820
PrivateKey = +HtKt2njk+z5eS2x+JcVlatzEyqBq+F3o62ISsmWnUo=

[Peer]
PublicKey = 9bmlFlwQ8AEu5g4KvsJF0vnRkI78mJ9I3KQVtd6ctQo=
AllowedIPs = 10.42.1.0/24, 10.10.11.231/32, 10.4.0.2/32
Endpoint = 18.202.215.77:23201
PersistentKeepalive = 5
```

The port on the endpoint changes after an handshake and after 30s kilo drops the existing connections applying the original configuration (with port 52820).

**Comment by squat** [comment]
@carlosrmendes thanks, that's exactly the info we needed. Your analysis is correct: every time that kilo tries to reconcile the configuration, it re-applies the config and cause WireGuard to interrupt all connections. It makes sense that the port gets changed when the connection is NATed. This means that in NAT scenarios Kilo cannot be so strict about ensuring peer ports stay the same. We have the three options IMO:
1. Make Kilo always ignore endpoint ports during reconciliation (easiest)
2. Add a new flag to Kilo to optionally enable non-strict endpoint checks during reconciliation
3. Add a new annotation to disable strict endpoint checks on an per-peer basis

What do you think? Endpoint roaming is supposed to be a core feature of WireGuard so 1 may be there correct choice. Indeed Kilo ignores endpoint changes for peers created via the Peer CRD since these IPs and ports can change at any time.

**Comment by carlosrmendes** [comment]
I agree with first option too.
But I think Kilo should also ignore the endpoint IP address, not just the port, because if I don't annotate the NATed node with `force-external-ip` the related peer on others nodes automatically set the endpoint with NAT public IP address and the Wireguard tunnel is created successfully.

**Comment by carlosrmendes** [comment]
Thinking better, probably the annotation option will fit better. The user should set which node (peer) are behind a NAT in order to decide or not the strict endpoint IP and port checks.

**Comment by squat** [comment]
Yes, I've been doing a lot of thinking on this question and it is non trivial. The hardest problem in creating the Kilo mesh is bootstrapping, ie discovering the peers (nodes) in the mesh and deciding what IPs to use for the endpoints. Kilo's approach to bootstrapping today is to make the entire mesh user-defined. If we take out reconciliation for these endpoints then we break this bootstrapping in certain scenarios. Taking out reconciliation is not crazy at all but it would require a new approach and algorithm to bootstrapping. In fact, I envision a future iteration where each Kilo node exposes a gRPC API to other mesh nodes and the nodes ping each other to establish the mesh and keep internal state to track the bootstrapping progress. However, this design needs to be fully fleshed out. Today, it may be easiest to continue with Kilo's current design and make the mesh design a user choice unless the user explicitly opts out and says "don't reconcile this node", ie sets an annotation.

**Comment by carlosrmendes** [comment]
I completely agree with you, good point of view @squat .
Yes, the mesh design being decided by the user is the best option according to the Kilo's current approach.

With this, how hard it will be add a new annotation to disable the endpoint checks in a NATed node?
I'm not a go expert, but I can try a pull request. :)

**Comment by squat** [comment]
@carlosrmendes I think it should be quite straight forward to make this change. Aythe heart of it, I think we want to do the following:
1. Create a method on the Mesh struct that synchronizes the endpoints of Nodes in the nodes map with the endpoints that are currently

**Comment by carlosrmendes** [comment]
hi again @squat, I'm continuing to test some uses cases with kilo. Now I'm testing the mixed topology, with one AWS location (AWS) and multiple edges locations.
My question is, with this topology it is supposed a pod in a private node in AWS (behind NAT, with no public-ip) could access to a pod/service in a an edge node on a specific location (behind NAT)?

**Comment by squat** [comment]
No, if they are both behind full NAT (ie neither using port-forwarding to have a stable WireGuard port) then they will neither of them will ever be able to establish an initial connection with the other. At least ONE of the two nodes must have a public IP + open port.

**Comment by carlosrmendes** [comment]
I have a master node on AWS with public-ip as a kilo leader.
But even if the edge node have it's own public ip, on the cloud private node I get an _no route to host_ error when I try to connect to the service ip of pod on the edge node.

**Comment by squat** [comment]
hmm I'm a bit confused. This sounds like it is a step back from where you were at the beginning of this issue

> I have one master node in region A with a public ip and a worker node in region B behind a NAT

Here you at least had a working route and could connect for a while before the connections were reset. What changed in the topology between the beginning and now?

**Comment by carlosrmendes** [comment]
So, I can connect successfully pods between *cloud master (kilo leader, public ip, location: aws)* to *edge node (nat, location: edge-1, keepalive: 5s)*.
Then I add a new node to the cluster on the cloud, *cloud node (location: aws)* on a private subnet, behind a nat.

Successfully connections:
pod on *cloud master* > pod on *edge node*
pod on *edge node* > pod on *cloud master*
pod on *edge node* > pod on *cloud node*

Unsuccessfully connections:
pod on *cloud node* > pod on *edge node*


Topology:
![image](https://user-images.githubusercontent.com/7363029/75796479-9d4a5680-5d6b-11ea-9c97-3a2d630533d9.png)

**Comment by squat** [comment]
@carlosrmendes thanks a lot for the graph, that is very helpful :)

can you please share the result of `ip route show all` from `cloud-node-3`?
Also, are the two nodes in AWS in different subnets? If so, what encapsulation settings are you using?

**Comment by carlosrmendes** [comment]
```
$ ip route show all
default via 10.30.116.1 dev ens5 proto dhcp src 10.30.116.202 metric 100
```

I try both `--encapsulate=never` and `--encapsulate=always`

**Comment by squat** [comment]
Hm.. can you please share the logs from Kilo on `cloud-node-3`? Those are not enough routes, which suggests that the pod is not running correctly.

Also, again, are the two AWS nodes in different subnets? If so, then please note that `--encapsulate=always` is required

**Comment by squat** [comment]
I realized today that the logic for using the presence of a non-zero keepalive value as a hint for ignoring changes to endpoints is backwards.  Persistent keepalives are sent by nodes behind NAT, not by the nodes outside of the NAT network. A node in the cloud outside of NAT will not send keepalives, so the persistent keepalive setting for its peers should be zero, which means it's not useful for it to look for non-zero keepalives for nodes with changing endpoints.
