### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by shnhrrsn** [squat/kilo#50]
Trying to setup kilo on a k3s cluster with three local nodes and one remote node.

All four nodes are showing this in the logs over and over:

```
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:37:36.742997397Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:37:44.982264977Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:39:57.25050876Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:39:57.402066518Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:39:59.314872301Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:40:09.406198759Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:40:16.246194963Z"}
{"caller":"mesh.go:639","component":"kilo","error":"address already in use","level":"error","ts":"2020-04-08T02:40:19.455699414Z"}
```

I'm not really sure what address is even in use so I can't debug on my end.

Any guidance?

**Comment by squat** [comment]
Hi @shnhrrsn that looks like Kilo is failing to set the WireGuard device in the `up` state. This can happen if the UDP socket that the WireGuard interface is configured to use is already taken by another process. By default, Kilo tries to run WireGuard on port UDP 51820. Can you share the output of `sudo ss -ulpn`? If the port is taken, you can modify the default port used by Kilo by appending `--port=<SOMEPORT>` to the Kilo DaemonSet.

**Comment by squat** [comment]
Hi @shnhrrsn any word? :)

**Comment by shnhrrsn** [comment]
Yup that was it, I actually had wireguard running from a previous attempt, thought I had it all cleaned up 🤦🏼‍♂️

**Comment by squat** [comment]
Ah that's classic. I'm glad you got it working!
