### ISSUE TITLE
Include video in readme.

### ISSUE THREAD

**Issue by hansbogert** [squat/kilo#63]
Is it correct that the video, https://www.youtube.com/watch?v=iPz_DAOOCKA, isn't referenced anywhere?
If so, that would be a shame, shall I make a PR?

**Comment by squat** [comment]
Hi @hansbogert yes, that's right, the video isn't linked anywhere in the repo :) please make the PR and I'll happy merge it :tada:

**Comment by hansbogert** [comment]
See #80
