### ISSUE TITLE
getting "received incomplete node" on the kilo leader and peer is not being created

### ISSUE THREAD

**Issue by carlosrmendes** [squat/kilo#64]
Hi @squat,
I have a node on a location B with all the peer created correctly, but its peer is not being created on the leader side, on location A, with this message showing on the kilo leader logs:
```
{"caller":"mesh.go:382","component":"kilo","event":"update","level":"debug","msg":"received incomplete node","node":{"Endpoint":{"DNS":"","IP":"192.168.50.13","Port":51820},"Key":"MHFPNW0zR3oxMFBlRkV0UUNRNGcxNTNvcTFnLzZnbE15WUJ1K2Q2d1JDTT0=","InternalIP":{"IP":"192.168.50.13","Mask":"////AA=="},"LastSeen":1594277590,"Leader":false,"Location":"admin-c7z87-oce-systel-ne-1","Name":"admin-c7z87-oce-systel-ne-1","PersistentKeepalive":5,"Subnet":{"IP":"10.42.39.0","Mask":"////AA=="},"WireGuardIP":{"IP":"10.40.0.2","Mask":"//8AAA=="}},"ts":"2020-07-11T10:52:59.048513869Z"}
```

Do you know what may be causing this?
Thanks in advance.

**Comment by carlosrmendes** [comment]
it was the wrong date on the host of location B

**Comment by squat** [comment]
very good to now! this was causing the node to appear as stale. Do you think it would be helpful for Kilo to log exactly _what_ makes a particular node incomplete? Might make debugging easier

**Comment by carlosrmendes** [comment]
yes, definitely the message of the real cause would help to debug 👍
