### ISSUE TITLE
WG in userspace / Running on systems without Wireguard kernel support?

### ISSUE THREAD

**Issue by platten** [squat/kilo#67]
Hello,

I was wondering if it is possible to run kilo with `wireguard-go` or `boringtun`, in userspace (instead of relying on kernel module). Is this on the roadmap?

Thanks!

**Comment by squat** [comment]
Paul,

Sorry for the delay, I just got back from vacation :)
Yes it's completely possible to run Kilo with boringtun (or any other
userspace implementation) today using a boringtun sidecar. I'd like to
create an example manifest to demonstrate this usage and add it to the
repo. If you want to contribute it yourself, please go for it! The main
thing to keep in mind is that the userspace implementation should create
the interface itself before Kilo runs and that the interface's name must be
specified in the kg container using the `--interface` flag.

-Lucas

**Comment by squat** [comment]
:tada: :taco:
