### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by SerialVelocity** [squat/kilo#73]
Hi Squat!

Could you tag releases with the updates/breaking changes?

Pulling from latest is pretty risky as it could take down a node if there is a bug. At the moment I pull from a sha hash instead but it becomes hard to figure out which version it corresponds to and whether there are any important changes/fixes I need to update to get.

**Comment by squat** [comment]
Hi @SerialVelocity this sounds very good to me. Kilo has been fairly stable for a while and has advanced a lot since last year. I think it's time to at least tag a v0.1.0. Does that SGTY?

**Comment by squat** [comment]
I just cut release `0.1.0` :tada: https://github.com/squat/kilo/releases/tag/0.1.0.
As a followup, I'll make sure that CI creates images for tags.

**Comment by squat** [comment]
wooo! the tag is on dockerhub :))) https://hub.docker.com/layers/squat/kilo/0.1.0/images/sha256-4fd831af093a047e6ed16b0a6cdf09afcb56ee9069864b710fe354bc28855f3e?context=explore

I'll closed this as resolved for now

**Comment by SerialVelocity** [comment]
Thank you!
