### ISSUE TITLE
difference between kilo-k3s.yaml and kilo-k3s-flannel.yaml

### ISSUE THREAD

**Issue by Ehco1996** [squat/kilo#78]
i am confuse about it , please help me out

**Comment by squat** [comment]
Hi @Ehco1996, kilo-k3s.yaml installs Kilo to be the only CNI provider in a k3s cluster kilo-k3s-flannel.yaml installs Kilo in compatibility mode so that it can run in a k3s cluster that *already* has Flannel installed. See: https://github.com/squat/kilo#add-on-mode

**Comment by Ehco1996** [comment]
thanks a lot ~
