### ISSUE TITLE
Use existing interface?

### ISSUE THREAD

**Issue by OJFord** [squat/kilo#8]
Will Kilo pick up an existing Wireguard interface on the host?

To be clear, I'd consider it a feature (though it's conceivably an anti-feature I suppose) - it would mean having it [bound to a physical interface in a different network namespace](https://www.wireguard.com/netns/#the-new-namespace-solution) was automatically supported.

**Comment by squat** [comment]
Hm no this is not supported. Kilo expects to fully control the WireGuard namespace as well as set up routes to other nodes (and pod CIDRs) in the cluster via either the wireguard or internal interface. It would certainly be possible to add a small patch to Kilo to optionally use an existing WireGuard iface (Kilo would still controll the configuration for the iface, just not create it), however, the Kilo container’s namespace (host namespace) would also need to have an internal iface to set up routes for intra-location communication, unless you are encrypting ALL node-node communication over wg.
