### ISSUE TITLE
kgctl - incorrect multi-cluster peers configuration on Ubuntu 20.04 with Ubuntu wireguard-tools v1.0.20200513

### ISSUE THREAD

**Issue by AntonOfTheWoods** [squat/kilo#83]
For those of us not yet well schooled in how wireguard works, the docs are a little light on details. I just had to work around what is probably a very obvious bug/missing feature in `kgctl`. It took me several hours to work it out unfortunately!!! 

When I execute `showconf` on `kgctl` version `425796ec4e75d266fe8cc5a87fcdde8ec1026c4f`, it gives me the public IP of the peer node in the `allowedIPs`, which means that by default (on Ubuntu?) a route gets created for the public ip of the endpoint to be transferred via `kilo0`. Because that is also the endpoint, nothing happens.

This is on a cheapo VPS that only has a public IP, and in the node config everywhere, eg.
```
...
  status:
    addresses:
    - address: XXX.XXX.XXX.XXX (this is the PUBLIC IP)
      type: InternalIP
...
```

The *only* way I was able to get things to work was to force `kilo.squat.ai/force-internal-ip` to a value I will never use (55.55.55.55 :-)).
Is there a known easy workaround or is my nasty hack the best we can do for the moment?

**Comment by squat** [comment]
Hi @AntonOfTheWoods good debugging :) this is an unfortunate side effect of nodes with no private networking and Kilo's assumption today that your nodes have a private network. There is an existing issue to track enabling Kilo to operate without private networking: https://github.com/squat/kilo/issues/15
Let's close this issue and track the progress there. Note: I'm definitely happy to accept contributions for this feature :)))
