### ISSUE TITLE
Guide on how to remove kilo safely

### ISSUE THREAD

**Issue by pratikbalar** [squat/kilo#86]
Hello,

I'm using kilo in Multi-cluster Services with k3s clusters, it's **amazing** BTW, i need little help do delete kilo without any breakage. i have already make sure that nothing is dependent.

Thank you

**Comment by squat** [comment]
Hi @pratikbalar thanks for the support! You can directly delete the Kilo DaemonSet from the cluster. This will "uninstall" Kilo. That's it! Note, any multi cluster connectivity will stop working when uninstalled.

**Comment by pratikbalar** [comment]
@squat wow. fast as flash, let me do that then I'll get back to you

**Comment by pratikbalar** [comment]
Hello @squat sorry for late, it worked, thanks for guiding.
 .
