### ISSUE TITLE
Confusing instructions for installing WireGuard using CoreOS installer DaemonSet on other distros

### ISSUE THREAD

**Issue by rstreics** [squat/kilo#89]
Hi Squat
Kernel installation fails because script in init container `wireguard-driver-installer` fails to download
`CoreOS_Image_Signing_Key.asc` from coreos webpage(404),[link to repo line](https://github.com/squat/modulus/blob/master/modulus#L121)

**Comment by squat** [comment]
Hi @rstreics, this WireGuard installer tool was only meant to work with CoreOS Container Linux and it's fork, Railcar Linux. It will not work with any other Linux distro. However, Container Linux has been End Of Lifed and thus the installer tool fails. There is an issue tracking continuing support for Railcar Linux in the repo for this installer: https://github.com/squat/modulus/pull/16 however this is orthogonal to Kilo. The Kilo documentation provides this example to show how you could get going on that particular Linux distro. Do you think maybe that that line of the readme is confusing? Is so, then I'd happily merge a PR to remove it :)))

**Comment by rstreics** [comment]
Hi @squat, thx for quick response.  Rereading `Installation` part more carefully it does say `for Container Linux`, but providing installation guide that doesn't work anymore due to EOL is bit confusing. 

My 2 cents:  Maybe readme could be updated to reflect what's needs to be done (listing kernel modules that's need to be installed etc..) and providing that init container script as template for installation.

**Comment by SerialVelocity** [comment]
@rstreics I would recommend switching to the Fedora CoreOS. The kernel is new enough to have the WireGuard module built in.
