### ISSUE TITLE
Applying `kilo.yaml` gives error

### ISSUE THREAD

**Issue by jihoon-seo** [squat/kilo#9]
Hi

I am trying to apply Kilo on K8s cluster, but an error appears when I `kubectl apply -f kilo.yaml`.

# What I want to do
* One node is on AWS.
* Another node is on GCP.
* I want to make a K8s cluster, with one+ master node (on AWS) and one+ worker node (on GCP).

# WireGuard
`root@VmOnAWS# wg show all` (WireGuard Server, `10.10.10.10`)
```
interface: wg0
  public key: (masked)
  private key: (hidden)
  listening port: 51820

peer: (masked)
  endpoint: 34.97.48.xxx:51820
  allowed ips: 10.10.10.12/32
  latest handshake: 1 minute, 30 seconds ago
  transfer: 297.40 MiB received, 1.47 GiB sent
```

`root@VmOnGCP# wg show all` (WireGuard Client, `10.10.10.12`)
```
interface: wg0
  public key: (masked)
  private key: (hidden)
  listening port: 51820

peer: (masked)
  endpoint: 15.164.170.xxx:51820
  allowed ips: 10.10.10.10/32
  latest handshake: 1 minute, 24 seconds ago
  transfer: 1.47 GiB received, 297.44 MiB sent
  persistent keepalive: every 25 seconds
```

# K8s cluster
`# kubectl get nodes -o wide`
```
NAME              STATUS     ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-17-xx   NotReady   master   24m   v1.15.0   172.31.17.xxx   <none>        Ubuntu 18.04.2 LTS   4.15.0-1044-aws   docker://18.9.7
nodes-wg2         NotReady   <none>   21m   v1.15.0   10.174.0.xxx    <none>        Ubuntu 18.04.2 LTS   4.15.0-1037-gcp   docker://18.9.7
```
* Node `ip-172-31-17-xx` is on AWS.
* Node `nodes-wg2` is on GCP.
* Since I have not installed a pod network add-on yet, the status of nodes is `NotReady`.

# Applying Kilo

`# kubectl annotate node ip-172-31-17-xx kilo.squat.ai/location="aws"`
```
node/ip-172-31-17-xx annotated
```

`# kubectl annotate node nodes-wg2 kilo.squat.ai/location="gcp"`
```
node/nodes-wg2 annotated
```

`# kubectl apply -f https://raw.githubusercontent.com/squat/kilo/master/manifests/kilo-kubeadm.yaml`
```
configmap/kilo created
serviceaccount/kilo created
clusterrole.rbac.authorization.k8s.io/kilo created
clusterrolebinding.rbac.authorization.k8s.io/kilo created
error: error validating "https://raw.githubusercontent.com/squat/kilo/master/manifests/kilo-kubeadm.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in
io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

`# kubectl apply -f https://raw.githubusercontent.com/squat/kilo/master/manifests/kilo-kubeadm.yaml --validate=false`
```
configmap/kilo unchanged
serviceaccount/kilo unchanged
clusterrole.rbac.authorization.k8s.io/kilo unchanged
clusterrolebinding.rbac.authorization.k8s.io/kilo unchanged
The DaemonSet "kilo" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/name":"kilo"}: `selector` does not match template `labels`
```

---

Is there a way to resolve this issue/problem?

**Comment by squat** [comment]
Hi @jihoon-seo,

I can confirm this error. This is due to the recent migration in DaemonSet API from extensions/v1beta1 to apps/v1. The old API defaulted the selector to the labels of the DaemonSet, whereas the new API does not default this field. I’ll post a fix asap.

**Comment by jihoon-seo** [comment]
Ok I got it.
Thank you for your fast response and dedication to this project!

**Comment by squat** [comment]
@jihoon-seo I pushed an update and confirmed that master is now working :) please take a look again and re-open if you have any trouble
